using System.Collections.Generic;
using WriterTycoon.WorkCreation.Genres;
using WriterTycoon.WorkCreation.Topics;

namespace WriterTycoon.WorkCreation.Rater
{
    public enum Compatibility
    {
        Excellent,
        Good,
        Neutral,
        Poor,
        Terrible
    }

    public class GenreTopicCompatibility
    {
        private readonly Dictionary<GenreType, Dictionary<TopicType, Compatibility>> genreTopicCompatibilities;

        public GenreTopicCompatibility()
        {
            // Create a new Dictionary
            genreTopicCompatibilities = new();

            // Add keys and values
            DeployActionCompatibilities();
            DeployAdventureCompatibilities();
            DeployContemporaryFictionCompatibilities();
            DeployFantasyCompatibilities();
        }

        private void DeployActionCompatibilities()
        {
            if (genreTopicCompatibilities == null) return;

            // Create a list to store the compatible topics
            Dictionary<TopicType, Compatibility> compatibleTopics = new()
            {
                { TopicType.Agents, Compatibility.Excellent },
                { TopicType.Airplanes, Compatibility.Excellent },
                { TopicType.Aliens, Compatibility.Excellent },
                { TopicType.AncientCivilization, Compatibility.Good },
                { TopicType.Androids, Compatibility.Good },
                { TopicType.Angels, Compatibility.Terrible },
                { TopicType.Animals, Compatibility.Good },
                { TopicType.Apocalypse, Compatibility.Excellent },
                { TopicType.Archaeology, Compatibility.Poor },
                { TopicType.Archery, Compatibility.Excellent },
                { TopicType.Art, Compatibility.Terrible },
                { TopicType.Assassins, Compatibility.Excellent },
                { TopicType.Biology, Compatibility.Terrible },
                { TopicType.BountyHunters, Compatibility.Excellent },
                { TopicType.Cars, Compatibility.Good },
                { TopicType.Cards, Compatibility.Terrible },
                { TopicType.Chemistry, Compatibility.Neutral },
                { TopicType.Chess, Compatibility.Terrible },
                { TopicType.Cinema, Compatibility.Neutral },
                { TopicType.Circus, Compatibility.Neutral },
                { TopicType.Conspiracies, Compatibility.Good },
                { TopicType.Crime, Compatibility.Excellent },
                { TopicType.Curses, Compatibility.Good },
                { TopicType.Dancing, Compatibility.Poor },
                { TopicType.Demons, Compatibility.Excellent },
                { TopicType.Detective, Compatibility.Good },
                { TopicType.Dinosaurs, Compatibility.Excellent },
                { TopicType.Doctors, Compatibility.Terrible },
                { TopicType.Dogs, Compatibility.Poor },
                { TopicType.Dolls, Compatibility.Poor },
                { TopicType.Dragons, Compatibility.Excellent },
                { TopicType.Dreams, Compatibility.Good },
                { TopicType.Erotica, Compatibility.Neutral },
                { TopicType.Espionage, Compatibility.Excellent },
                { TopicType.Evolution, Compatibility.Neutral },
                { TopicType.Fey, Compatibility.Poor },
                { TopicType.Fashion, Compatibility.Terrible },
                { TopicType.Food, Compatibility.Neutral },
                { TopicType.Gambling, Compatibility.Poor },
                { TopicType.Games, Compatibility.Good },
                { TopicType.Gangs, Compatibility.Excellent },
                { TopicType.Gladiators, Compatibility.Excellent },
                { TopicType.Gods, Compatibility.Good },
                { TopicType.Hacking, Compatibility.Neutral },
                { TopicType.Heaven, Compatibility.Terrible },
                { TopicType.Heist, Compatibility.Good },
                { TopicType.Hell, Compatibility.Good },
                { TopicType.Hitmen, Compatibility.Excellent },
                { TopicType.Hunting, Compatibility.Excellent },
                { TopicType.Industrialization, Compatibility.Neutral },
                { TopicType.Insects, Compatibility.Poor },
                { TopicType.Journalism, Compatibility.Poor },
                { TopicType.Kaiju, Compatibility.Excellent },
                { TopicType.Language, Compatibility.Terrible },
                { TopicType.Mathematics, Compatibility.Terrible },
                { TopicType.Mecha, Compatibility.Excellent },
                { TopicType.Mermaids, Compatibility.Poor },
                { TopicType.Military, Compatibility.Excellent },
                { TopicType.Mummies, Compatibility.Good },
                { TopicType.Music, Compatibility.Terrible },
                { TopicType.Ninjas, Compatibility.Excellent },
                { TopicType.ParallelWorld, Compatibility.Neutral },
                { TopicType.Pets, Compatibility.Terrible },
                { TopicType.Photography, Compatibility.Terrible },
                { TopicType.Physics, Compatibility.Neutral },
                { TopicType.Pirates, Compatibility.Excellent },
                { TopicType.Plants, Compatibility.Terrible },
                { TopicType.Police, Compatibility.Good },
                { TopicType.Politics, Compatibility.Neutral },
                { TopicType.Prison, Compatibility.Good },
                { TopicType.Religion, Compatibility.Neutral },
                { TopicType.Revolution, Compatibility.Excellent },
                { TopicType.Samurai, Compatibility.Excellent },
                { TopicType.Sea, Compatibility.Neutral },
                { TopicType.SecretSociety, Compatibility.Good },
                { TopicType.Showbiz, Compatibility.Poor },
                { TopicType.Singing, Compatibility.Terrible },
                { TopicType.Space, Compatibility.Excellent },
                { TopicType.Sports, Compatibility.Neutral },
                { TopicType.StoneAge, Compatibility.Poor },
                { TopicType.Superheroes, Compatibility.Excellent },
                { TopicType.Supervillains, Compatibility.Excellent },
                { TopicType.Survival, Compatibility.Good },
                { TopicType.TimeTravel, Compatibility.Good },
                { TopicType.TreasureHunters, Compatibility.Good },
                { TopicType.University, Compatibility.Terrible },
                { TopicType.Vampires, Compatibility.Good },
                { TopicType.Vikings, Compatibility.Excellent },
                { TopicType.Viruses, Compatibility.Neutral },
                { TopicType.War, Compatibility.Excellent },
                { TopicType.Werewolves, Compatibility.Good },
                { TopicType.WildWest, Compatibility.Excellent },
                { TopicType.Wizardry, Compatibility.Good },
                { TopicType.Zombies, Compatibility.Excellent }
            };

            // Add the pair to the Dictionary
            genreTopicCompatibilities.Add(GenreType.Action, compatibleTopics);
        }

        private void DeployAdventureCompatibilities()
        {
            if (genreTopicCompatibilities == null) return;

            // Create a list to store the compatible topics
            Dictionary<TopicType, Compatibility> compatibleTopics = new()
            {
                { TopicType.Agents, Compatibility.Neutral },
                { TopicType.Airplanes, Compatibility.Neutral },
                { TopicType.Aliens, Compatibility.Good },
                { TopicType.AncientCivilization, Compatibility.Good },
                { TopicType.Androids, Compatibility.Neutral },
                { TopicType.Angels, Compatibility.Poor },
                { TopicType.Animals, Compatibility.Poor },
                { TopicType.Apocalypse, Compatibility.Excellent },
                { TopicType.Archaeology, Compatibility.Excellent },
                { TopicType.Archery, Compatibility.Neutral },
                { TopicType.Art, Compatibility.Poor },
                { TopicType.Assassins, Compatibility.Good },
                { TopicType.Biology, Compatibility.Neutral },
                { TopicType.BountyHunters, Compatibility.Excellent },
                { TopicType.Cars, Compatibility.Neutral },
                { TopicType.Cards, Compatibility.Terrible },
                { TopicType.Chemistry, Compatibility.Neutral },
                { TopicType.Chess, Compatibility.Terrible },
                { TopicType.Cinema, Compatibility.Neutral },
                { TopicType.Circus, Compatibility.Good },
                { TopicType.Conspiracies, Compatibility.Excellent },
                { TopicType.Crime, Compatibility.Excellent },
                { TopicType.Curses, Compatibility.Good },
                { TopicType.Dancing, Compatibility.Poor },
                { TopicType.Demons, Compatibility.Poor },
                { TopicType.Detective, Compatibility.Excellent },
                { TopicType.Dinosaurs, Compatibility.Excellent },
                { TopicType.Doctors, Compatibility.Terrible },
                { TopicType.Dogs, Compatibility.Neutral },
                { TopicType.Dolls, Compatibility.Poor },
                { TopicType.Dragons, Compatibility.Excellent },
                { TopicType.Dreams, Compatibility.Excellent },
                { TopicType.Erotica, Compatibility.Excellent },
                { TopicType.Espionage, Compatibility.Excellent },
                { TopicType.Evolution, Compatibility.Poor },
                { TopicType.Fey, Compatibility.Good },
                { TopicType.Fashion, Compatibility.Terrible },
                { TopicType.Food, Compatibility.Good },
                { TopicType.Gambling, Compatibility.Neutral },
                { TopicType.Games, Compatibility.Excellent },
                { TopicType.Gangs, Compatibility.Poor },
                { TopicType.Gladiators, Compatibility.Excellent },
                { TopicType.Gods, Compatibility.Neutral },
                { TopicType.Hacking, Compatibility.Excellent },
                { TopicType.Heaven, Compatibility.Terrible },
                { TopicType.Heist, Compatibility.Good },
                { TopicType.Hell, Compatibility.Terrible },
                { TopicType.Hitmen, Compatibility.Terrible },
                { TopicType.Hunting, Compatibility.Excellent },
                { TopicType.Industrialization, Compatibility.Terrible },
                { TopicType.Insects, Compatibility.Neutral },
                { TopicType.Journalism, Compatibility.Excellent },
                { TopicType.Kaiju, Compatibility.Excellent },
                { TopicType.Language, Compatibility.Terrible },
                { TopicType.Mathematics, Compatibility.Terrible },
                { TopicType.Mecha, Compatibility.Good },
                { TopicType.Mermaids, Compatibility.Good },
                { TopicType.Military, Compatibility.Terrible },
                { TopicType.Mummies, Compatibility.Excellent },
                { TopicType.Music, Compatibility.Neutral },
                { TopicType.Ninjas, Compatibility.Good },
                { TopicType.ParallelWorld, Compatibility.Excellent },
                { TopicType.Pets, Compatibility.Neutral },
                { TopicType.Photography, Compatibility.Good },
                { TopicType.Physics, Compatibility.Terrible },
                { TopicType.Pirates, Compatibility.Excellent },
                { TopicType.Plants, Compatibility.Terrible },
                { TopicType.Police, Compatibility.Poor },
                { TopicType.Politics, Compatibility.Terrible },
                { TopicType.Prison, Compatibility.Neutral },
                { TopicType.Religion, Compatibility.Terrible },
                { TopicType.Revolution, Compatibility.Neutral },
                { TopicType.Samurai, Compatibility.Good },
                { TopicType.Sea, Compatibility.Excellent },
                { TopicType.SecretSociety, Compatibility.Good },
                { TopicType.Showbiz, Compatibility.Neutral },
                { TopicType.Singing, Compatibility.Terrible },
                { TopicType.Space, Compatibility.Excellent },
                { TopicType.Sports, Compatibility.Poor },
                { TopicType.StoneAge, Compatibility.Good },
                { TopicType.Superheroes, Compatibility.Excellent },
                { TopicType.Supervillains, Compatibility.Poor },
                { TopicType.Survival, Compatibility.Good },
                { TopicType.TimeTravel, Compatibility.Excellent },
                { TopicType.TreasureHunters, Compatibility.Excellent },
                { TopicType.University, Compatibility.Terrible },
                { TopicType.Vampires, Compatibility.Neutral },
                { TopicType.Vikings, Compatibility.Neutral },
                { TopicType.Viruses, Compatibility.Terrible },
                { TopicType.War, Compatibility.Terrible },
                { TopicType.Werewolves, Compatibility.Neutral },
                { TopicType.WildWest, Compatibility.Excellent },
                { TopicType.Wizardry, Compatibility.Good },
                { TopicType.Zombies, Compatibility.Neutral }
            };

            // Add the pair to the Dictionary
            genreTopicCompatibilities.Add(GenreType.Adventure, compatibleTopics);
        }

        private void DeployContemporaryFictionCompatibilities()
        {
            if (genreTopicCompatibilities == null) return;

            // Create a list to store the compatible topics
            Dictionary<TopicType, Compatibility> compatibleTopics = new()
            {
                { TopicType.Agents, Compatibility.Terrible },
                { TopicType.Airplanes, Compatibility.Neutral },
                { TopicType.Aliens, Compatibility.Terrible },
                { TopicType.AncientCivilization, Compatibility.Terrible },
                { TopicType.Androids, Compatibility.Terrible },
                { TopicType.Angels, Compatibility.Terrible },
                { TopicType.Animals, Compatibility.Good },
                { TopicType.Apocalypse, Compatibility.Terrible },
                { TopicType.Archaeology, Compatibility.Neutral },
                { TopicType.Archery, Compatibility.Poor },
                { TopicType.Art, Compatibility.Excellent },
                { TopicType.Assassins, Compatibility.Terrible },
                { TopicType.Biology, Compatibility.Neutral },
                { TopicType.BountyHunters, Compatibility.Terrible },
                { TopicType.Cars, Compatibility.Poor },
                { TopicType.Cards, Compatibility.Good },
                { TopicType.Chemistry, Compatibility.Neutral },
                { TopicType.Chess, Compatibility.Excellent },
                { TopicType.Cinema, Compatibility.Excellent },
                { TopicType.Circus, Compatibility.Good },
                { TopicType.Conspiracies, Compatibility.Poor },
                { TopicType.Crime, Compatibility.Poor },
                { TopicType.Curses, Compatibility.Terrible },
                { TopicType.Dancing, Compatibility.Excellent },
                { TopicType.Demons, Compatibility.Terrible },
                { TopicType.Detective, Compatibility.Poor },
                { TopicType.Dinosaurs, Compatibility.Terrible },
                { TopicType.Doctors, Compatibility.Good },
                { TopicType.Dogs, Compatibility.Good },
                { TopicType.Dolls, Compatibility.Neutral },
                { TopicType.Dragons, Compatibility.Terrible },
                { TopicType.Dreams, Compatibility.Neutral },
                { TopicType.Erotica, Compatibility.Good },
                { TopicType.Espionage, Compatibility.Terrible },
                { TopicType.Evolution, Compatibility.Terrible },
                { TopicType.Fey, Compatibility.Terrible },
                { TopicType.Fashion, Compatibility.Excellent },
                { TopicType.Food, Compatibility.Excellent },
                { TopicType.Gambling, Compatibility.Good },
                { TopicType.Games, Compatibility.Neutral },
                { TopicType.Gangs, Compatibility.Terrible },
                { TopicType.Gladiators, Compatibility.Terrible },
                { TopicType.Gods, Compatibility.Terrible },
                { TopicType.Hacking, Compatibility.Neutral },
                { TopicType.Heaven, Compatibility.Terrible },
                { TopicType.Heist, Compatibility.Poor },
                { TopicType.Hell, Compatibility.Terrible },
                { TopicType.Hitmen, Compatibility.Terrible },
                { TopicType.Hunting, Compatibility.Good },
                { TopicType.Industrialization, Compatibility.Excellent },
                { TopicType.Insects, Compatibility.Poor },
                { TopicType.Journalism, Compatibility.Excellent },
                { TopicType.Kaiju, Compatibility.Terrible },
                { TopicType.Language, Compatibility.Excellent },
                { TopicType.Mathematics, Compatibility.Excellent },
                { TopicType.Mecha, Compatibility.Terrible },
                { TopicType.Mermaids, Compatibility.Terrible },
                { TopicType.Military, Compatibility.Neutral },
                { TopicType.Mummies, Compatibility.Terrible },
                { TopicType.Music, Compatibility.Excellent },
                { TopicType.Ninjas, Compatibility.Terrible },
                { TopicType.ParallelWorld, Compatibility.Poor },
                { TopicType.Pets, Compatibility.Good },
                { TopicType.Photography, Compatibility.Good },
                { TopicType.Physics, Compatibility.Good },
                { TopicType.Pirates, Compatibility.Terrible },
                { TopicType.Plants, Compatibility.Good },
                { TopicType.Police, Compatibility.Poor },
                { TopicType.Politics, Compatibility.Good },
                { TopicType.Prison, Compatibility.Neutral },
                { TopicType.Religion, Compatibility.Terrible },
                { TopicType.Revolution, Compatibility.Good },
                { TopicType.Samurai, Compatibility.Terrible },
                { TopicType.Sea, Compatibility.Neutral },
                { TopicType.SecretSociety, Compatibility.Terrible },
                { TopicType.Showbiz, Compatibility.Good },
                { TopicType.Singing, Compatibility.Neutral },
                { TopicType.Space, Compatibility.Poor },
                { TopicType.Sports, Compatibility.Good },
                { TopicType.StoneAge, Compatibility.Terrible },
                { TopicType.Superheroes, Compatibility.Terrible },
                { TopicType.Supervillains, Compatibility.Terrible },
                { TopicType.Survival, Compatibility.Poor },
                { TopicType.TimeTravel, Compatibility.Terrible },
                { TopicType.TreasureHunters, Compatibility.Terrible },
                { TopicType.University, Compatibility.Excellent },
                { TopicType.Vampires, Compatibility.Terrible },
                { TopicType.Vikings, Compatibility.Terrible },
                { TopicType.Viruses, Compatibility.Poor },
                { TopicType.War, Compatibility.Good },
                { TopicType.Werewolves, Compatibility.Terrible },
                { TopicType.WildWest, Compatibility.Terrible },
                { TopicType.Wizardry, Compatibility.Terrible },
                { TopicType.Zombies, Compatibility.Terrible }
            };

            // Add the pair to the Dictionary
            genreTopicCompatibilities.Add(GenreType.ContemporaryFiction, compatibleTopics);
        }

        private void DeployFantasyCompatibilities()
        {
            if (genreTopicCompatibilities == null) return;

            // Create a list to store the compatible topics
            Dictionary<TopicType, Compatibility> compatibleTopics = new()
            {
                { TopicType.Agents, Compatibility.Good },
                { TopicType.Airplanes, Compatibility.Terrible },
                { TopicType.Aliens, Compatibility.Terrible },
                { TopicType.AncientCivilization, Compatibility.Neutral },
                { TopicType.Androids, Compatibility.Terrible },
                { TopicType.Angels, Compatibility.Neutral },
                { TopicType.Animals, Compatibility.Neutral },
                { TopicType.Apocalypse, Compatibility.Neutral },
                { TopicType.Archaeology, Compatibility.Poor },
                { TopicType.Archery, Compatibility.Good },
                { TopicType.Art, Compatibility.Poor },
                { TopicType.Assassins, Compatibility.Good },
                { TopicType.Biology, Compatibility.Terrible },
                { TopicType.BountyHunters, Compatibility.Neutral },
                { TopicType.Cars, Compatibility.Terrible },
                { TopicType.Cards, Compatibility.Neutral },
                { TopicType.Chemistry, Compatibility.Terrible },
                { TopicType.Chess, Compatibility.Good },
                { TopicType.Cinema, Compatibility.Terrible },
                { TopicType.Circus, Compatibility.Neutral },
                { TopicType.Conspiracies, Compatibility.Terrible },
                { TopicType.Crime, Compatibility.Good },
                { TopicType.Curses, Compatibility.Good },
                { TopicType.Dancing, Compatibility.Terrible },
                { TopicType.Demons, Compatibility.Good },
                { TopicType.Detective, Compatibility.Neutral },
                { TopicType.Dinosaurs, Compatibility.Neutral },
                { TopicType.Doctors, Compatibility.Terrible },
                { TopicType.Dogs, Compatibility.Neutral },
                { TopicType.Dolls, Compatibility.Neutral },
                { TopicType.Dragons, Compatibility.Excellent },
                { TopicType.Dreams, Compatibility.Excellent },
                { TopicType.Erotica, Compatibility.Excellent },
                { TopicType.Espionage, Compatibility.Poor },
                { TopicType.Evolution, Compatibility.Terrible },
                { TopicType.Fey, Compatibility.Excellent },
                { TopicType.Fashion, Compatibility.Terrible },
                { TopicType.Food, Compatibility.Poor },
                { TopicType.Gambling, Compatibility.Poor },
                { TopicType.Games, Compatibility.Excellent },
                { TopicType.Gangs, Compatibility.Terrible },
                { TopicType.Gladiators, Compatibility.Good },
                { TopicType.Gods, Compatibility.Excellent },
                { TopicType.Hacking, Compatibility.Terrible },
                { TopicType.Heaven, Compatibility.Good },
                { TopicType.Heist, Compatibility.Neutral },
                { TopicType.Hell, Compatibility.Good },
                { TopicType.Hitmen, Compatibility.Terrible },
                { TopicType.Hunting, Compatibility.Poor },
                { TopicType.Industrialization, Compatibility.Terrible },
                { TopicType.Insects, Compatibility.Neutral },
                { TopicType.Journalism, Compatibility.Terrible },
                { TopicType.Kaiju, Compatibility.Good },
                { TopicType.Language, Compatibility.Excellent },
                { TopicType.Mathematics, Compatibility.Good },
                { TopicType.Mecha, Compatibility.Poor },
                { TopicType.Mermaids, Compatibility.Good },
                { TopicType.Military, Compatibility.Terrible },
                { TopicType.Mummies, Compatibility.Excellent },
                { TopicType.Music, Compatibility.Neutral },
                { TopicType.Ninjas, Compatibility.Good },
                { TopicType.ParallelWorld, Compatibility.Excellent },
                { TopicType.Pets, Compatibility.Neutral },
                { TopicType.Photography, Compatibility.Terrible },
                { TopicType.Physics, Compatibility.Terrible },
                { TopicType.Pirates, Compatibility.Excellent },
                { TopicType.Plants, Compatibility.Neutral },
                { TopicType.Police, Compatibility.Terrible },
                { TopicType.Politics, Compatibility.Good },
                { TopicType.Prison, Compatibility.Terrible },
                { TopicType.Religion, Compatibility.Good },
                { TopicType.Revolution, Compatibility.Neutral },
                { TopicType.Samurai, Compatibility.Good },
                { TopicType.Sea, Compatibility.Neutral },
                { TopicType.SecretSociety, Compatibility.Good },
                { TopicType.Showbiz, Compatibility.Terrible },
                { TopicType.Singing, Compatibility.Terrible },
                { TopicType.Space, Compatibility.Terrible },
                { TopicType.Sports, Compatibility.Terrible },
                { TopicType.StoneAge, Compatibility.Terrible },
                { TopicType.Superheroes, Compatibility.Excellent },
                { TopicType.Supervillains, Compatibility.Excellent },
                { TopicType.Survival, Compatibility.Poor },
                { TopicType.TimeTravel, Compatibility.Excellent },
                { TopicType.TreasureHunters, Compatibility.Excellent },
                { TopicType.University, Compatibility.Neutral },
                { TopicType.Vampires, Compatibility.Excellent },
                { TopicType.Vikings, Compatibility.Excellent },
                { TopicType.Viruses, Compatibility.Neutral },
                { TopicType.War, Compatibility.Good },
                { TopicType.Werewolves, Compatibility.Excellent },
                { TopicType.WildWest, Compatibility.Neutral },
                { TopicType.Wizardry, Compatibility.Excellent },
                { TopicType.Zombies, Compatibility.Excellent }
            };

            // Add the pair to the Dictionary
            genreTopicCompatibilities.Add(GenreType.Fantasy, compatibleTopics);
        }
    }
}