using System.Collections.Generic;
using WriterTycoon.WorkCreation.Genres;
using WriterTycoon.WorkCreation.Topics;

namespace WriterTycoon.WorkCreation.Compatibility
{
    public enum Compatibility
    {
        None,
        Excellent,
        Good,
        Neutral,
        Poor,
        Terrible
    }

    public class GenreTopicCompatibility
    {
        private readonly Dictionary<GenreType, Dictionary<TopicType, Compatibility>> genreTopicCompatibilities;

        public GenreTopicCompatibility()
        {
            // Create a new Dictionary
            genreTopicCompatibilities = new();

            // Add keys and values
            DeployActionCompatibilities();
            DeployAdventureCompatibilities();
            DeployContemporaryFictionCompatibilities();
            DeployFantasyCompatibilities();
            DeployHistoricalFantasyCompatibilities();
            DeployMysteryCompatibilities();
            DeployNonfictionCompatibilities();
            DeployRomanceCompatibilities();
            DeployScienceFictionCompatibilities();
            DeployThrillerCompatibilities();
        }

        /// <summary>
        /// Get the Compatibility of a Genre-Topic pairing
        /// </summary>
        public Compatibility GetCompatibility(GenreType genre, TopicType topic)
        {
            // Try to get a value from the dictionary using the Genre
            if(genreTopicCompatibilities.TryGetValue(
                genre, 
                out Dictionary<TopicType, Compatibility> topicCompatibilities)
            )
            {
                // If successful, try to get a value from the retrieved dictionary using the
                // Topic
                if(topicCompatibilities.TryGetValue(topic, out Compatibility compatibility))
                {
                    // If successful, return the compatibility
                    return compatibility;
                }

                // If not able to retrieve a value, return none
                return Compatibility.None;
            }

            // If not able to retrieve a value, return none
            return Compatibility.None;
        }

        /// <summary>
        /// Deploy all Action-Topic compatibilities
        /// </summary>
        private void DeployActionCompatibilities()
        {
            if (genreTopicCompatibilities == null) return;

            // Create a list to store the compatible topics
            Dictionary<TopicType, Compatibility> compatibleTopics = new()
            {
                { TopicType.Agents, Compatibility.Excellent },
                { TopicType.Airplanes, Compatibility.Excellent },
                { TopicType.Aliens, Compatibility.Excellent },
                { TopicType.AncientCivilization, Compatibility.Good },
                { TopicType.Androids, Compatibility.Good },
                { TopicType.Angels, Compatibility.Terrible },
                { TopicType.Animals, Compatibility.Good },
                { TopicType.Apocalypse, Compatibility.Excellent },
                { TopicType.Archaeology, Compatibility.Poor },
                { TopicType.Archery, Compatibility.Excellent },
                { TopicType.Art, Compatibility.Terrible },
                { TopicType.Assassins, Compatibility.Excellent },
                { TopicType.Biology, Compatibility.Terrible },
                { TopicType.BountyHunters, Compatibility.Excellent },
                { TopicType.Cars, Compatibility.Good },
                { TopicType.Cards, Compatibility.Terrible },
                { TopicType.Chemistry, Compatibility.Neutral },
                { TopicType.Chess, Compatibility.Terrible },
                { TopicType.Cinema, Compatibility.Neutral },
                { TopicType.Circus, Compatibility.Neutral },
                { TopicType.Conspiracies, Compatibility.Good },
                { TopicType.Crime, Compatibility.Excellent },
                { TopicType.Curses, Compatibility.Good },
                { TopicType.Dancing, Compatibility.Poor },
                { TopicType.Demons, Compatibility.Excellent },
                { TopicType.Detective, Compatibility.Good },
                { TopicType.Dinosaurs, Compatibility.Excellent },
                { TopicType.Doctors, Compatibility.Terrible },
                { TopicType.Dogs, Compatibility.Poor },
                { TopicType.Dolls, Compatibility.Poor },
                { TopicType.Dragons, Compatibility.Excellent },
                { TopicType.Dreams, Compatibility.Good },
                { TopicType.Erotica, Compatibility.Neutral },
                { TopicType.Espionage, Compatibility.Excellent },
                { TopicType.Evolution, Compatibility.Neutral },
                { TopicType.Fey, Compatibility.Poor },
                { TopicType.Fashion, Compatibility.Terrible },
                { TopicType.Food, Compatibility.Neutral },
                { TopicType.Gambling, Compatibility.Poor },
                { TopicType.Games, Compatibility.Good },
                { TopicType.Gangs, Compatibility.Excellent },
                { TopicType.Gladiators, Compatibility.Excellent },
                { TopicType.Gods, Compatibility.Good },
                { TopicType.Hacking, Compatibility.Neutral },
                { TopicType.Heaven, Compatibility.Terrible },
                { TopicType.Heist, Compatibility.Good },
                { TopicType.Hell, Compatibility.Good },
                { TopicType.Hitmen, Compatibility.Excellent },
                { TopicType.Hunting, Compatibility.Excellent },
                { TopicType.Industrialization, Compatibility.Neutral },
                { TopicType.Insects, Compatibility.Poor },
                { TopicType.Journalism, Compatibility.Poor },
                { TopicType.Kaiju, Compatibility.Excellent },
                { TopicType.Language, Compatibility.Terrible },
                { TopicType.Mathematics, Compatibility.Terrible },
                { TopicType.Mecha, Compatibility.Excellent },
                { TopicType.Mermaids, Compatibility.Poor },
                { TopicType.Military, Compatibility.Excellent },
                { TopicType.Mummies, Compatibility.Good },
                { TopicType.Music, Compatibility.Terrible },
                { TopicType.Ninjas, Compatibility.Excellent },
                { TopicType.ParallelWorld, Compatibility.Neutral },
                { TopicType.Pets, Compatibility.Terrible },
                { TopicType.Photography, Compatibility.Terrible },
                { TopicType.Physics, Compatibility.Neutral },
                { TopicType.Pirates, Compatibility.Excellent },
                { TopicType.Plants, Compatibility.Terrible },
                { TopicType.Police, Compatibility.Good },
                { TopicType.Politics, Compatibility.Neutral },
                { TopicType.Prison, Compatibility.Good },
                { TopicType.Religion, Compatibility.Neutral },
                { TopicType.Revolution, Compatibility.Excellent },
                { TopicType.Samurai, Compatibility.Excellent },
                { TopicType.Sea, Compatibility.Neutral },
                { TopicType.SecretSociety, Compatibility.Good },
                { TopicType.Showbiz, Compatibility.Poor },
                { TopicType.Singing, Compatibility.Terrible },
                { TopicType.Space, Compatibility.Excellent },
                { TopicType.Sports, Compatibility.Neutral },
                { TopicType.StoneAge, Compatibility.Poor },
                { TopicType.Superheroes, Compatibility.Excellent },
                { TopicType.Supervillains, Compatibility.Excellent },
                { TopicType.Survival, Compatibility.Good },
                { TopicType.TimeTravel, Compatibility.Good },
                { TopicType.TreasureHunters, Compatibility.Good },
                { TopicType.University, Compatibility.Terrible },
                { TopicType.Vampires, Compatibility.Good },
                { TopicType.Vikings, Compatibility.Excellent },
                { TopicType.Viruses, Compatibility.Neutral },
                { TopicType.War, Compatibility.Excellent },
                { TopicType.Werewolves, Compatibility.Good },
                { TopicType.WildWest, Compatibility.Excellent },
                { TopicType.Wizardry, Compatibility.Good },
                { TopicType.Zombies, Compatibility.Excellent }
            };

            // Add the pair to the Dictionary
            genreTopicCompatibilities.Add(GenreType.Action, compatibleTopics);
        }

        /// <summary>
        /// Deploy all Adventure-Topic compatibilities
        /// </summary>
        private void DeployAdventureCompatibilities()
        {
            if (genreTopicCompatibilities == null) return;

            // Create a list to store the compatible topics
            Dictionary<TopicType, Compatibility> compatibleTopics = new()
            {
                { TopicType.Agents, Compatibility.Neutral },
                { TopicType.Airplanes, Compatibility.Neutral },
                { TopicType.Aliens, Compatibility.Good },
                { TopicType.AncientCivilization, Compatibility.Good },
                { TopicType.Androids, Compatibility.Neutral },
                { TopicType.Angels, Compatibility.Poor },
                { TopicType.Animals, Compatibility.Poor },
                { TopicType.Apocalypse, Compatibility.Excellent },
                { TopicType.Archaeology, Compatibility.Excellent },
                { TopicType.Archery, Compatibility.Neutral },
                { TopicType.Art, Compatibility.Poor },
                { TopicType.Assassins, Compatibility.Good },
                { TopicType.Biology, Compatibility.Neutral },
                { TopicType.BountyHunters, Compatibility.Excellent },
                { TopicType.Cars, Compatibility.Neutral },
                { TopicType.Cards, Compatibility.Terrible },
                { TopicType.Chemistry, Compatibility.Neutral },
                { TopicType.Chess, Compatibility.Terrible },
                { TopicType.Cinema, Compatibility.Neutral },
                { TopicType.Circus, Compatibility.Good },
                { TopicType.Conspiracies, Compatibility.Excellent },
                { TopicType.Crime, Compatibility.Excellent },
                { TopicType.Curses, Compatibility.Good },
                { TopicType.Dancing, Compatibility.Poor },
                { TopicType.Demons, Compatibility.Poor },
                { TopicType.Detective, Compatibility.Excellent },
                { TopicType.Dinosaurs, Compatibility.Excellent },
                { TopicType.Doctors, Compatibility.Terrible },
                { TopicType.Dogs, Compatibility.Neutral },
                { TopicType.Dolls, Compatibility.Poor },
                { TopicType.Dragons, Compatibility.Excellent },
                { TopicType.Dreams, Compatibility.Excellent },
                { TopicType.Erotica, Compatibility.Excellent },
                { TopicType.Espionage, Compatibility.Excellent },
                { TopicType.Evolution, Compatibility.Poor },
                { TopicType.Fey, Compatibility.Good },
                { TopicType.Fashion, Compatibility.Terrible },
                { TopicType.Food, Compatibility.Good },
                { TopicType.Gambling, Compatibility.Neutral },
                { TopicType.Games, Compatibility.Excellent },
                { TopicType.Gangs, Compatibility.Poor },
                { TopicType.Gladiators, Compatibility.Excellent },
                { TopicType.Gods, Compatibility.Neutral },
                { TopicType.Hacking, Compatibility.Excellent },
                { TopicType.Heaven, Compatibility.Terrible },
                { TopicType.Heist, Compatibility.Good },
                { TopicType.Hell, Compatibility.Terrible },
                { TopicType.Hitmen, Compatibility.Terrible },
                { TopicType.Hunting, Compatibility.Excellent },
                { TopicType.Industrialization, Compatibility.Terrible },
                { TopicType.Insects, Compatibility.Neutral },
                { TopicType.Journalism, Compatibility.Excellent },
                { TopicType.Kaiju, Compatibility.Excellent },
                { TopicType.Language, Compatibility.Terrible },
                { TopicType.Mathematics, Compatibility.Terrible },
                { TopicType.Mecha, Compatibility.Good },
                { TopicType.Mermaids, Compatibility.Good },
                { TopicType.Military, Compatibility.Terrible },
                { TopicType.Mummies, Compatibility.Excellent },
                { TopicType.Music, Compatibility.Neutral },
                { TopicType.Ninjas, Compatibility.Good },
                { TopicType.ParallelWorld, Compatibility.Excellent },
                { TopicType.Pets, Compatibility.Neutral },
                { TopicType.Photography, Compatibility.Good },
                { TopicType.Physics, Compatibility.Terrible },
                { TopicType.Pirates, Compatibility.Excellent },
                { TopicType.Plants, Compatibility.Terrible },
                { TopicType.Police, Compatibility.Poor },
                { TopicType.Politics, Compatibility.Terrible },
                { TopicType.Prison, Compatibility.Neutral },
                { TopicType.Religion, Compatibility.Terrible },
                { TopicType.Revolution, Compatibility.Neutral },
                { TopicType.Samurai, Compatibility.Good },
                { TopicType.Sea, Compatibility.Excellent },
                { TopicType.SecretSociety, Compatibility.Good },
                { TopicType.Showbiz, Compatibility.Neutral },
                { TopicType.Singing, Compatibility.Terrible },
                { TopicType.Space, Compatibility.Excellent },
                { TopicType.Sports, Compatibility.Poor },
                { TopicType.StoneAge, Compatibility.Good },
                { TopicType.Superheroes, Compatibility.Excellent },
                { TopicType.Supervillains, Compatibility.Poor },
                { TopicType.Survival, Compatibility.Good },
                { TopicType.TimeTravel, Compatibility.Excellent },
                { TopicType.TreasureHunters, Compatibility.Excellent },
                { TopicType.University, Compatibility.Terrible },
                { TopicType.Vampires, Compatibility.Neutral },
                { TopicType.Vikings, Compatibility.Neutral },
                { TopicType.Viruses, Compatibility.Terrible },
                { TopicType.War, Compatibility.Terrible },
                { TopicType.Werewolves, Compatibility.Neutral },
                { TopicType.WildWest, Compatibility.Excellent },
                { TopicType.Wizardry, Compatibility.Good },
                { TopicType.Zombies, Compatibility.Neutral }
            };

            // Add the pair to the Dictionary
            genreTopicCompatibilities.Add(GenreType.Adventure, compatibleTopics);
        }

        /// <summary>
        /// Deploy all Contemporary Fiction-Topic compatibilities
        /// </summary>
        private void DeployContemporaryFictionCompatibilities()
        {
            if (genreTopicCompatibilities == null) return;

            // Create a list to store the compatible topics
            Dictionary<TopicType, Compatibility> compatibleTopics = new()
            {
                { TopicType.Agents, Compatibility.Terrible },
                { TopicType.Airplanes, Compatibility.Neutral },
                { TopicType.Aliens, Compatibility.Terrible },
                { TopicType.AncientCivilization, Compatibility.Terrible },
                { TopicType.Androids, Compatibility.Terrible },
                { TopicType.Angels, Compatibility.Terrible },
                { TopicType.Animals, Compatibility.Good },
                { TopicType.Apocalypse, Compatibility.Terrible },
                { TopicType.Archaeology, Compatibility.Neutral },
                { TopicType.Archery, Compatibility.Poor },
                { TopicType.Art, Compatibility.Excellent },
                { TopicType.Assassins, Compatibility.Terrible },
                { TopicType.Biology, Compatibility.Neutral },
                { TopicType.BountyHunters, Compatibility.Terrible },
                { TopicType.Cars, Compatibility.Poor },
                { TopicType.Cards, Compatibility.Good },
                { TopicType.Chemistry, Compatibility.Neutral },
                { TopicType.Chess, Compatibility.Excellent },
                { TopicType.Cinema, Compatibility.Excellent },
                { TopicType.Circus, Compatibility.Good },
                { TopicType.Conspiracies, Compatibility.Poor },
                { TopicType.Crime, Compatibility.Poor },
                { TopicType.Curses, Compatibility.Terrible },
                { TopicType.Dancing, Compatibility.Excellent },
                { TopicType.Demons, Compatibility.Terrible },
                { TopicType.Detective, Compatibility.Poor },
                { TopicType.Dinosaurs, Compatibility.Terrible },
                { TopicType.Doctors, Compatibility.Good },
                { TopicType.Dogs, Compatibility.Good },
                { TopicType.Dolls, Compatibility.Neutral },
                { TopicType.Dragons, Compatibility.Terrible },
                { TopicType.Dreams, Compatibility.Neutral },
                { TopicType.Erotica, Compatibility.Good },
                { TopicType.Espionage, Compatibility.Terrible },
                { TopicType.Evolution, Compatibility.Terrible },
                { TopicType.Fey, Compatibility.Terrible },
                { TopicType.Fashion, Compatibility.Excellent },
                { TopicType.Food, Compatibility.Excellent },
                { TopicType.Gambling, Compatibility.Good },
                { TopicType.Games, Compatibility.Neutral },
                { TopicType.Gangs, Compatibility.Terrible },
                { TopicType.Gladiators, Compatibility.Terrible },
                { TopicType.Gods, Compatibility.Terrible },
                { TopicType.Hacking, Compatibility.Neutral },
                { TopicType.Heaven, Compatibility.Terrible },
                { TopicType.Heist, Compatibility.Poor },
                { TopicType.Hell, Compatibility.Terrible },
                { TopicType.Hitmen, Compatibility.Terrible },
                { TopicType.Hunting, Compatibility.Good },
                { TopicType.Industrialization, Compatibility.Excellent },
                { TopicType.Insects, Compatibility.Poor },
                { TopicType.Journalism, Compatibility.Excellent },
                { TopicType.Kaiju, Compatibility.Terrible },
                { TopicType.Language, Compatibility.Excellent },
                { TopicType.Mathematics, Compatibility.Excellent },
                { TopicType.Mecha, Compatibility.Terrible },
                { TopicType.Mermaids, Compatibility.Terrible },
                { TopicType.Military, Compatibility.Neutral },
                { TopicType.Mummies, Compatibility.Terrible },
                { TopicType.Music, Compatibility.Excellent },
                { TopicType.Ninjas, Compatibility.Terrible },
                { TopicType.ParallelWorld, Compatibility.Poor },
                { TopicType.Pets, Compatibility.Good },
                { TopicType.Photography, Compatibility.Good },
                { TopicType.Physics, Compatibility.Good },
                { TopicType.Pirates, Compatibility.Terrible },
                { TopicType.Plants, Compatibility.Good },
                { TopicType.Police, Compatibility.Poor },
                { TopicType.Politics, Compatibility.Good },
                { TopicType.Prison, Compatibility.Neutral },
                { TopicType.Religion, Compatibility.Terrible },
                { TopicType.Revolution, Compatibility.Good },
                { TopicType.Samurai, Compatibility.Terrible },
                { TopicType.Sea, Compatibility.Neutral },
                { TopicType.SecretSociety, Compatibility.Terrible },
                { TopicType.Showbiz, Compatibility.Good },
                { TopicType.Singing, Compatibility.Neutral },
                { TopicType.Space, Compatibility.Poor },
                { TopicType.Sports, Compatibility.Good },
                { TopicType.StoneAge, Compatibility.Terrible },
                { TopicType.Superheroes, Compatibility.Terrible },
                { TopicType.Supervillains, Compatibility.Terrible },
                { TopicType.Survival, Compatibility.Poor },
                { TopicType.TimeTravel, Compatibility.Terrible },
                { TopicType.TreasureHunters, Compatibility.Terrible },
                { TopicType.University, Compatibility.Excellent },
                { TopicType.Vampires, Compatibility.Terrible },
                { TopicType.Vikings, Compatibility.Terrible },
                { TopicType.Viruses, Compatibility.Poor },
                { TopicType.War, Compatibility.Good },
                { TopicType.Werewolves, Compatibility.Terrible },
                { TopicType.WildWest, Compatibility.Terrible },
                { TopicType.Wizardry, Compatibility.Terrible },
                { TopicType.Zombies, Compatibility.Terrible }
            };

            // Add the pair to the Dictionary
            genreTopicCompatibilities.Add(GenreType.ContemporaryFiction, compatibleTopics);
        }

        /// <summary>
        /// Deploy all Fantasy-Topic compatibilities
        /// </summary>
        private void DeployFantasyCompatibilities()
        {
            if (genreTopicCompatibilities == null) return;

            // Create a list to store the compatible topics
            Dictionary<TopicType, Compatibility> compatibleTopics = new()
            {
                { TopicType.Agents, Compatibility.Good },
                { TopicType.Airplanes, Compatibility.Terrible },
                { TopicType.Aliens, Compatibility.Terrible },
                { TopicType.AncientCivilization, Compatibility.Neutral },
                { TopicType.Androids, Compatibility.Terrible },
                { TopicType.Angels, Compatibility.Neutral },
                { TopicType.Animals, Compatibility.Neutral },
                { TopicType.Apocalypse, Compatibility.Neutral },
                { TopicType.Archaeology, Compatibility.Poor },
                { TopicType.Archery, Compatibility.Good },
                { TopicType.Art, Compatibility.Poor },
                { TopicType.Assassins, Compatibility.Good },
                { TopicType.Biology, Compatibility.Terrible },
                { TopicType.BountyHunters, Compatibility.Neutral },
                { TopicType.Cars, Compatibility.Terrible },
                { TopicType.Cards, Compatibility.Neutral },
                { TopicType.Chemistry, Compatibility.Terrible },
                { TopicType.Chess, Compatibility.Good },
                { TopicType.Cinema, Compatibility.Terrible },
                { TopicType.Circus, Compatibility.Neutral },
                { TopicType.Conspiracies, Compatibility.Terrible },
                { TopicType.Crime, Compatibility.Good },
                { TopicType.Curses, Compatibility.Good },
                { TopicType.Dancing, Compatibility.Terrible },
                { TopicType.Demons, Compatibility.Good },
                { TopicType.Detective, Compatibility.Neutral },
                { TopicType.Dinosaurs, Compatibility.Neutral },
                { TopicType.Doctors, Compatibility.Terrible },
                { TopicType.Dogs, Compatibility.Neutral },
                { TopicType.Dolls, Compatibility.Neutral },
                { TopicType.Dragons, Compatibility.Excellent },
                { TopicType.Dreams, Compatibility.Excellent },
                { TopicType.Erotica, Compatibility.Excellent },
                { TopicType.Espionage, Compatibility.Poor },
                { TopicType.Evolution, Compatibility.Terrible },
                { TopicType.Fey, Compatibility.Excellent },
                { TopicType.Fashion, Compatibility.Terrible },
                { TopicType.Food, Compatibility.Poor },
                { TopicType.Gambling, Compatibility.Poor },
                { TopicType.Games, Compatibility.Excellent },
                { TopicType.Gangs, Compatibility.Terrible },
                { TopicType.Gladiators, Compatibility.Good },
                { TopicType.Gods, Compatibility.Excellent },
                { TopicType.Hacking, Compatibility.Terrible },
                { TopicType.Heaven, Compatibility.Good },
                { TopicType.Heist, Compatibility.Neutral },
                { TopicType.Hell, Compatibility.Good },
                { TopicType.Hitmen, Compatibility.Terrible },
                { TopicType.Hunting, Compatibility.Poor },
                { TopicType.Industrialization, Compatibility.Terrible },
                { TopicType.Insects, Compatibility.Neutral },
                { TopicType.Journalism, Compatibility.Terrible },
                { TopicType.Kaiju, Compatibility.Good },
                { TopicType.Language, Compatibility.Excellent },
                { TopicType.Mathematics, Compatibility.Good },
                { TopicType.Mecha, Compatibility.Poor },
                { TopicType.Mermaids, Compatibility.Good },
                { TopicType.Military, Compatibility.Terrible },
                { TopicType.Mummies, Compatibility.Excellent },
                { TopicType.Music, Compatibility.Neutral },
                { TopicType.Ninjas, Compatibility.Good },
                { TopicType.ParallelWorld, Compatibility.Excellent },
                { TopicType.Pets, Compatibility.Neutral },
                { TopicType.Photography, Compatibility.Terrible },
                { TopicType.Physics, Compatibility.Terrible },
                { TopicType.Pirates, Compatibility.Excellent },
                { TopicType.Plants, Compatibility.Neutral },
                { TopicType.Police, Compatibility.Terrible },
                { TopicType.Politics, Compatibility.Good },
                { TopicType.Prison, Compatibility.Terrible },
                { TopicType.Religion, Compatibility.Good },
                { TopicType.Revolution, Compatibility.Neutral },
                { TopicType.Samurai, Compatibility.Good },
                { TopicType.Sea, Compatibility.Neutral },
                { TopicType.SecretSociety, Compatibility.Good },
                { TopicType.Showbiz, Compatibility.Terrible },
                { TopicType.Singing, Compatibility.Terrible },
                { TopicType.Space, Compatibility.Terrible },
                { TopicType.Sports, Compatibility.Terrible },
                { TopicType.StoneAge, Compatibility.Terrible },
                { TopicType.Superheroes, Compatibility.Excellent },
                { TopicType.Supervillains, Compatibility.Excellent },
                { TopicType.Survival, Compatibility.Poor },
                { TopicType.TimeTravel, Compatibility.Excellent },
                { TopicType.TreasureHunters, Compatibility.Excellent },
                { TopicType.University, Compatibility.Neutral },
                { TopicType.Vampires, Compatibility.Excellent },
                { TopicType.Vikings, Compatibility.Excellent },
                { TopicType.Viruses, Compatibility.Neutral },
                { TopicType.War, Compatibility.Good },
                { TopicType.Werewolves, Compatibility.Excellent },
                { TopicType.WildWest, Compatibility.Neutral },
                { TopicType.Wizardry, Compatibility.Excellent },
                { TopicType.Zombies, Compatibility.Excellent }
            };

            // Add the pair to the Dictionary
            genreTopicCompatibilities.Add(GenreType.Fantasy, compatibleTopics);
        }

        /// <summary>
        /// Deploy all Historical Fantasy-Topic compatibilities
        /// </summary>
        private void DeployHistoricalFantasyCompatibilities()
        {
            if (genreTopicCompatibilities == null) return;

            // Create a list to store the compatible topics
            Dictionary<TopicType, Compatibility> compatibleTopics = new()
            {
                { TopicType.Agents, Compatibility.Good },
                { TopicType.Airplanes, Compatibility.Good },
                { TopicType.Aliens, Compatibility.Neutral },
                { TopicType.AncientCivilization, Compatibility.Excellent },
                { TopicType.Androids, Compatibility.Terrible },
                { TopicType.Angels, Compatibility.Neutral },
                { TopicType.Animals, Compatibility.Neutral },
                { TopicType.Apocalypse, Compatibility.Terrible },
                { TopicType.Archaeology, Compatibility.Excellent },
                { TopicType.Archery, Compatibility.Neutral },
                { TopicType.Art, Compatibility.Neutral },
                { TopicType.Assassins, Compatibility.Good },
                { TopicType.Biology, Compatibility.Terrible },
                { TopicType.BountyHunters, Compatibility.Poor },
                { TopicType.Cars, Compatibility.Excellent },
                { TopicType.Cards, Compatibility.Neutral },
                { TopicType.Chemistry, Compatibility.Terrible },
                { TopicType.Chess, Compatibility.Excellent },
                { TopicType.Cinema, Compatibility.Excellent },
                { TopicType.Circus, Compatibility.Good },
                { TopicType.Conspiracies, Compatibility.Excellent },
                { TopicType.Crime, Compatibility.Good },
                { TopicType.Curses, Compatibility.Poor },
                { TopicType.Dancing, Compatibility.Neutral },
                { TopicType.Demons, Compatibility.Terrible },
                { TopicType.Detective, Compatibility.Neutral },
                { TopicType.Dinosaurs, Compatibility.Good },
                { TopicType.Doctors, Compatibility.Neutral },
                { TopicType.Dogs, Compatibility.Neutral },
                { TopicType.Dolls, Compatibility.Neutral },
                { TopicType.Dragons, Compatibility.Terrible },
                { TopicType.Dreams, Compatibility.Poor },
                { TopicType.Erotica, Compatibility.Neutral },
                { TopicType.Espionage, Compatibility.Excellent },
                { TopicType.Evolution, Compatibility.Good },
                { TopicType.Fey, Compatibility.Terrible },
                { TopicType.Fashion, Compatibility.Good },
                { TopicType.Food, Compatibility.Good },
                { TopicType.Gambling, Compatibility.Neutral },
                { TopicType.Games, Compatibility.Good },
                { TopicType.Gangs, Compatibility.Good },
                { TopicType.Gladiators, Compatibility.Excellent },
                { TopicType.Gods, Compatibility.Terrible },
                { TopicType.Hacking, Compatibility.Neutral },
                { TopicType.Heaven, Compatibility.Terrible },
                { TopicType.Heist, Compatibility.Poor },
                { TopicType.Hell, Compatibility.Terrible },
                { TopicType.Hitmen, Compatibility.Terrible },
                { TopicType.Hunting, Compatibility.Neutral },
                { TopicType.Industrialization, Compatibility.Excellent },
                { TopicType.Insects, Compatibility.Neutral },
                { TopicType.Journalism, Compatibility.Excellent },
                { TopicType.Kaiju, Compatibility.Terrible },
                { TopicType.Language, Compatibility.Good },
                { TopicType.Mathematics, Compatibility.Good },
                { TopicType.Mecha, Compatibility.Terrible },
                { TopicType.Mermaids, Compatibility.Terrible },
                { TopicType.Military, Compatibility.Excellent },
                { TopicType.Mummies, Compatibility.Terrible },
                { TopicType.Music, Compatibility.Excellent },
                { TopicType.Ninjas, Compatibility.Neutral },
                { TopicType.ParallelWorld, Compatibility.Good },
                { TopicType.Pets, Compatibility.Poor },
                { TopicType.Photography, Compatibility.Good },
                { TopicType.Physics, Compatibility.Neutral },
                { TopicType.Pirates, Compatibility.Neutral },
                { TopicType.Plants, Compatibility.Neutral },
                { TopicType.Police, Compatibility.Good },
                { TopicType.Politics, Compatibility.Excellent },
                { TopicType.Prison, Compatibility.Good },
                { TopicType.Religion, Compatibility.Excellent },
                { TopicType.Revolution, Compatibility.Excellent },
                { TopicType.Samurai, Compatibility.Good },
                { TopicType.Sea, Compatibility.Neutral },
                { TopicType.SecretSociety, Compatibility.Good },
                { TopicType.Showbiz, Compatibility.Good },
                { TopicType.Singing, Compatibility.Poor },
                { TopicType.Space, Compatibility.Neutral },
                { TopicType.Sports, Compatibility.Neutral },
                { TopicType.StoneAge, Compatibility.Excellent },
                { TopicType.Superheroes, Compatibility.Poor },
                { TopicType.Supervillains, Compatibility.Poor },
                { TopicType.Survival, Compatibility.Good },
                { TopicType.TimeTravel, Compatibility.Neutral },
                { TopicType.TreasureHunters, Compatibility.Good },
                { TopicType.University, Compatibility.Neutral },
                { TopicType.Vampires, Compatibility.Neutral },
                { TopicType.Vikings, Compatibility.Excellent },
                { TopicType.Viruses, Compatibility.Terrible },
                { TopicType.War, Compatibility.Excellent },
                { TopicType.Werewolves, Compatibility.Terrible },
                { TopicType.WildWest, Compatibility.Excellent },
                { TopicType.Wizardry, Compatibility.Poor },
                { TopicType.Zombies, Compatibility.Terrible }
            };

            // Add the pair to the Dictionary
            genreTopicCompatibilities.Add(GenreType.HistoricalFiction, compatibleTopics);
        }

        /// <summary>
        /// Deploy all Mystery-Topic compatibilities
        /// </summary>
        private void DeployMysteryCompatibilities()
        {
            if (genreTopicCompatibilities == null) return;

            // Create a list to store the compatible topics
            Dictionary<TopicType, Compatibility> compatibleTopics = new()
            {
                { TopicType.Agents, Compatibility.Good },
                { TopicType.Airplanes, Compatibility.Poor },
                { TopicType.Aliens, Compatibility.Good },
                { TopicType.AncientCivilization, Compatibility.Terrible },
                { TopicType.Androids, Compatibility.Poor },
                { TopicType.Angels, Compatibility.Terrible },
                { TopicType.Animals, Compatibility.Terrible },
                { TopicType.Apocalypse, Compatibility.Neutral },
                { TopicType.Archaeology, Compatibility.Good },
                { TopicType.Archery, Compatibility.Poor },
                { TopicType.Art, Compatibility.Terrible },
                { TopicType.Assassins, Compatibility.Excellent },
                { TopicType.Biology, Compatibility.Terrible },
                { TopicType.BountyHunters, Compatibility.Poor },
                { TopicType.Cars, Compatibility.Terrible },
                { TopicType.Cards, Compatibility.Neutral },
                { TopicType.Chemistry, Compatibility.Terrible },
                { TopicType.Chess, Compatibility.Terrible },
                { TopicType.Cinema, Compatibility.Terrible },
                { TopicType.Circus, Compatibility.Good },
                { TopicType.Conspiracies, Compatibility.Excellent },
                { TopicType.Crime, Compatibility.Neutral },
                { TopicType.Curses, Compatibility.Good },
                { TopicType.Dancing, Compatibility.Neutral },
                { TopicType.Demons, Compatibility.Terrible },
                { TopicType.Detective, Compatibility.Excellent },
                { TopicType.Dinosaurs, Compatibility.Terrible },
                { TopicType.Doctors, Compatibility.Neutral },
                { TopicType.Dogs, Compatibility.Poor },
                { TopicType.Dolls, Compatibility.Poor },
                { TopicType.Dragons, Compatibility.Terrible },
                { TopicType.Dreams, Compatibility.Good },
                { TopicType.Erotica, Compatibility.Excellent },
                { TopicType.Espionage, Compatibility.Excellent },
                { TopicType.Evolution, Compatibility.Terrible },
                { TopicType.Fey, Compatibility.Excellent },
                { TopicType.Fashion, Compatibility.Poor },
                { TopicType.Food, Compatibility.Terrible },
                { TopicType.Gambling, Compatibility.Terrible },
                { TopicType.Games, Compatibility.Terrible },
                { TopicType.Gangs, Compatibility.Poor },
                { TopicType.Gladiators, Compatibility.Poor },
                { TopicType.Gods, Compatibility.Poor },
                { TopicType.Hacking, Compatibility.Excellent },
                { TopicType.Heaven, Compatibility.Terrible },
                { TopicType.Heist, Compatibility.Neutral },
                { TopicType.Hell, Compatibility.Terrible },
                { TopicType.Hitmen, Compatibility.Good },
                { TopicType.Hunting, Compatibility.Terrible },
                { TopicType.Industrialization, Compatibility.Terrible },
                { TopicType.Insects, Compatibility.Terrible },
                { TopicType.Journalism, Compatibility.Excellent },
                { TopicType.Kaiju, Compatibility.Neutral },
                { TopicType.Language, Compatibility.Neutral },
                { TopicType.Mathematics, Compatibility.Neutral },
                { TopicType.Mecha, Compatibility.Neutral },
                { TopicType.Mermaids, Compatibility.Poor },
                { TopicType.Military, Compatibility.Terrible },
                { TopicType.Mummies, Compatibility.Good },
                { TopicType.Music, Compatibility.Poor },
                { TopicType.Ninjas, Compatibility.Good },
                { TopicType.ParallelWorld, Compatibility.Good },
                { TopicType.Pets, Compatibility.Poor },
                { TopicType.Photography, Compatibility.Good },
                { TopicType.Physics, Compatibility.Neutral },
                { TopicType.Pirates, Compatibility.Poor },
                { TopicType.Plants, Compatibility.Neutral },
                { TopicType.Police, Compatibility.Good },
                { TopicType.Politics, Compatibility.Good },
                { TopicType.Prison, Compatibility.Neutral },
                { TopicType.Religion, Compatibility.Poor },
                { TopicType.Revolution, Compatibility.Terrible },
                { TopicType.Samurai, Compatibility.Poor },
                { TopicType.Sea, Compatibility.Good },
                { TopicType.SecretSociety, Compatibility.Excellent },
                { TopicType.Showbiz, Compatibility.Neutral },
                { TopicType.Singing, Compatibility.Poor },
                { TopicType.Space, Compatibility.Excellent },
                { TopicType.Sports, Compatibility.Terrible },
                { TopicType.StoneAge, Compatibility.Terrible },
                { TopicType.Superheroes, Compatibility.Neutral },
                { TopicType.Supervillains, Compatibility.Neutral },
                { TopicType.Survival, Compatibility.Poor },
                { TopicType.TimeTravel, Compatibility.Good },
                { TopicType.TreasureHunters, Compatibility.Good },
                { TopicType.University, Compatibility.Neutral },
                { TopicType.Vampires, Compatibility.Neutral },
                { TopicType.Vikings, Compatibility.Terrible },
                { TopicType.Viruses, Compatibility.Excellent },
                { TopicType.War, Compatibility.Poor },
                { TopicType.Werewolves, Compatibility.Neutral },
                { TopicType.WildWest, Compatibility.Poor },
                { TopicType.Wizardry, Compatibility.Neutral },
                { TopicType.Zombies, Compatibility.Good }
            };

            // Add the pair to the Dictionary
            genreTopicCompatibilities.Add(GenreType.Mystery, compatibleTopics);
        }

        /// <summary>
        /// Deploy all Non-fiction-Topic compatibilities
        /// </summary>
        private void DeployNonfictionCompatibilities()
        {
            if (genreTopicCompatibilities == null) return;

            // Create a list to store the compatible topics
            Dictionary<TopicType, Compatibility> compatibleTopics = new()
            {
                { TopicType.Agents, Compatibility.Neutral },
                { TopicType.Airplanes, Compatibility.Good },
                { TopicType.Aliens, Compatibility.Terrible },
                { TopicType.AncientCivilization, Compatibility.Excellent },
                { TopicType.Androids, Compatibility.Terrible },
                { TopicType.Angels, Compatibility.Terrible },
                { TopicType.Animals, Compatibility.Good },
                { TopicType.Apocalypse, Compatibility.Terrible },
                { TopicType.Archaeology, Compatibility.Excellent },
                { TopicType.Archery, Compatibility.Neutral },
                { TopicType.Art, Compatibility.Excellent },
                { TopicType.Assassins, Compatibility.Neutral },
                { TopicType.Biology, Compatibility.Good },
                { TopicType.BountyHunters, Compatibility.Terrible },
                { TopicType.Cars, Compatibility.Excellent },
                { TopicType.Cards, Compatibility.Good },
                { TopicType.Chemistry, Compatibility.Good },
                { TopicType.Chess, Compatibility.Excellent },
                { TopicType.Cinema, Compatibility.Excellent },
                { TopicType.Circus, Compatibility.Good },
                { TopicType.Conspiracies, Compatibility.Neutral },
                { TopicType.Crime, Compatibility.Good },
                { TopicType.Curses, Compatibility.Poor },
                { TopicType.Dancing, Compatibility.Good },
                { TopicType.Demons, Compatibility.Terrible },
                { TopicType.Detective, Compatibility.Neutral },
                { TopicType.Dinosaurs, Compatibility.Good },
                { TopicType.Doctors, Compatibility.Good },
                { TopicType.Dogs, Compatibility.Good },
                { TopicType.Dolls, Compatibility.Neutral },
                { TopicType.Dragons, Compatibility.Terrible },
                { TopicType.Dreams, Compatibility.Terrible },
                { TopicType.Erotica, Compatibility.Terrible },
                { TopicType.Espionage, Compatibility.Good },
                { TopicType.Evolution, Compatibility.Good },
                { TopicType.Fey, Compatibility.Terrible },
                { TopicType.Fashion, Compatibility.Excellent },
                { TopicType.Food, Compatibility.Excellent },
                { TopicType.Gambling, Compatibility.Neutral },
                { TopicType.Games, Compatibility.Good },
                { TopicType.Gangs, Compatibility.Good },
                { TopicType.Gladiators, Compatibility.Good },
                { TopicType.Gods, Compatibility.Terrible },
                { TopicType.Hacking, Compatibility.Excellent },
                { TopicType.Heaven, Compatibility.Terrible },
                { TopicType.Heist, Compatibility.Poor },
                { TopicType.Hell, Compatibility.Terrible },
                { TopicType.Hitmen, Compatibility.Poor },
                { TopicType.Hunting, Compatibility.Neutral },
                { TopicType.Industrialization, Compatibility.Excellent },
                { TopicType.Insects, Compatibility.Good },
                { TopicType.Journalism, Compatibility.Excellent },
                { TopicType.Kaiju, Compatibility.Terrible },
                { TopicType.Language, Compatibility.Good },
                { TopicType.Mathematics, Compatibility.Good },
                { TopicType.Mecha, Compatibility.Terrible },
                { TopicType.Mermaids, Compatibility.Terrible },
                { TopicType.Military, Compatibility.Excellent },
                { TopicType.Mummies, Compatibility.Neutral },
                { TopicType.Music, Compatibility.Excellent },
                { TopicType.Ninjas, Compatibility.Neutral },
                { TopicType.ParallelWorld, Compatibility.Terrible },
                { TopicType.Pets, Compatibility.Neutral },
                { TopicType.Photography, Compatibility.Good },
                { TopicType.Physics, Compatibility.Good },
                { TopicType.Pirates, Compatibility.Neutral },
                { TopicType.Plants, Compatibility.Good },
                { TopicType.Police, Compatibility.Good },
                { TopicType.Politics, Compatibility.Excellent },
                { TopicType.Prison, Compatibility.Neutral },
                { TopicType.Religion, Compatibility.Good },
                { TopicType.Revolution, Compatibility.Good },
                { TopicType.Samurai, Compatibility.Neutral },
                { TopicType.Sea, Compatibility.Good },
                { TopicType.SecretSociety, Compatibility.Poor },
                { TopicType.Showbiz, Compatibility.Excellent },
                { TopicType.Singing, Compatibility.Good },
                { TopicType.Space, Compatibility.Neutral },
                { TopicType.Sports, Compatibility.Good },
                { TopicType.StoneAge, Compatibility.Excellent },
                { TopicType.Superheroes, Compatibility.Terrible },
                { TopicType.Supervillains, Compatibility.Terrible },
                { TopicType.Survival, Compatibility.Excellent },
                { TopicType.TimeTravel, Compatibility.Terrible },
                { TopicType.TreasureHunters, Compatibility.Poor },
                { TopicType.University, Compatibility.Excellent },
                { TopicType.Vampires, Compatibility.Terrible },
                { TopicType.Vikings, Compatibility.Neutral },
                { TopicType.Viruses, Compatibility.Good },
                { TopicType.War, Compatibility.Excellent },
                { TopicType.Werewolves, Compatibility.Terrible },
                { TopicType.WildWest, Compatibility.Poor },
                { TopicType.Wizardry, Compatibility.Terrible },
                { TopicType.Zombies, Compatibility.Terrible }
            };

            // Add the pair to the Dictionary
            genreTopicCompatibilities.Add(GenreType.Nonfiction, compatibleTopics);
        }

        /// <summary>
        /// Deploy all Romance-Topic compatibilities
        /// </summary>
        private void DeployRomanceCompatibilities()
        {
            if (genreTopicCompatibilities == null) return;

            // Create a list to store the compatible topics
            Dictionary<TopicType, Compatibility> compatibleTopics = new()
            {
                { TopicType.Agents, Compatibility.Poor },
                { TopicType.Airplanes, Compatibility.Terrible },
                { TopicType.Aliens, Compatibility.Terrible },
                { TopicType.AncientCivilization, Compatibility.Neutral },
                { TopicType.Androids, Compatibility.Neutral },
                { TopicType.Angels, Compatibility.Terrible },
                { TopicType.Animals, Compatibility.Terrible },
                { TopicType.Apocalypse, Compatibility.Good },
                { TopicType.Archaeology, Compatibility.Terrible },
                { TopicType.Archery, Compatibility.Neutral },
                { TopicType.Art, Compatibility.Excellent },
                { TopicType.Assassins, Compatibility.Terrible },
                { TopicType.Biology, Compatibility.Neutral },
                { TopicType.BountyHunters, Compatibility.Terrible },
                { TopicType.Cars, Compatibility.Poor },
                { TopicType.Cards, Compatibility.Neutral },
                { TopicType.Chemistry, Compatibility.Neutral },
                { TopicType.Chess, Compatibility.Good },
                { TopicType.Cinema, Compatibility.Neutral },
                { TopicType.Circus, Compatibility.Neutral },
                { TopicType.Conspiracies, Compatibility.Poor },
                { TopicType.Crime, Compatibility.Good },
                { TopicType.Curses, Compatibility.Terrible },
                { TopicType.Dancing, Compatibility.Excellent },
                { TopicType.Demons, Compatibility.Terrible },
                { TopicType.Detective, Compatibility.Neutral },
                { TopicType.Dinosaurs, Compatibility.Terrible },
                { TopicType.Doctors, Compatibility.Neutral },
                { TopicType.Dogs, Compatibility.Poor },
                { TopicType.Dolls, Compatibility.Poor },
                { TopicType.Dragons, Compatibility.Terrible },
                { TopicType.Dreams, Compatibility.Excellent },
                { TopicType.Erotica, Compatibility.Excellent },
                { TopicType.Espionage, Compatibility.Poor },
                { TopicType.Evolution, Compatibility.Terrible },
                { TopicType.Fey, Compatibility.Excellent },
                { TopicType.Fashion, Compatibility.Good },
                { TopicType.Food, Compatibility.Neutral },
                { TopicType.Gambling, Compatibility.Poor },
                { TopicType.Games, Compatibility.Poor },
                { TopicType.Gangs, Compatibility.Terrible },
                { TopicType.Gladiators, Compatibility.Terrible },
                { TopicType.Gods, Compatibility.Neutral },
                { TopicType.Hacking, Compatibility.Terrible },
                { TopicType.Heaven, Compatibility.Terrible },
                { TopicType.Heist, Compatibility.Good },
                { TopicType.Hell, Compatibility.Terrible },
                { TopicType.Hitmen, Compatibility.Terrible },
                { TopicType.Hunting, Compatibility.Terrible },
                { TopicType.Industrialization, Compatibility.Terrible },
                { TopicType.Insects, Compatibility.Terrible },
                { TopicType.Journalism, Compatibility.Neutral },
                { TopicType.Kaiju, Compatibility.Terrible },
                { TopicType.Language, Compatibility.Good },
                { TopicType.Mathematics, Compatibility.Good },
                { TopicType.Mecha, Compatibility.Neutral },
                { TopicType.Mermaids, Compatibility.Good },
                { TopicType.Military, Compatibility.Terrible },
                { TopicType.Mummies, Compatibility.Terrible },
                { TopicType.Music, Compatibility.Excellent },
                { TopicType.Ninjas, Compatibility.Poor },
                { TopicType.ParallelWorld, Compatibility.Neutral },
                { TopicType.Pets, Compatibility.Good },
                { TopicType.Photography, Compatibility.Excellent },
                { TopicType.Physics, Compatibility.Neutral },
                { TopicType.Pirates, Compatibility.Neutral },
                { TopicType.Plants, Compatibility.Poor },
                { TopicType.Police, Compatibility.Poor },
                { TopicType.Politics, Compatibility.Good },
                { TopicType.Prison, Compatibility.Poor },
                { TopicType.Religion, Compatibility.Neutral },
                { TopicType.Revolution, Compatibility.Good },
                { TopicType.Samurai, Compatibility.Terrible },
                { TopicType.Sea, Compatibility.Good },
                { TopicType.SecretSociety, Compatibility.Poor },
                { TopicType.Showbiz, Compatibility.Excellent },
                { TopicType.Singing, Compatibility.Excellent },
                { TopicType.Space, Compatibility.Neutral },
                { TopicType.Sports, Compatibility.Good },
                { TopicType.StoneAge, Compatibility.Terrible },
                { TopicType.Superheroes, Compatibility.Good },
                { TopicType.Supervillains, Compatibility.Good },
                { TopicType.Survival, Compatibility.Terrible },
                { TopicType.TimeTravel, Compatibility.Good },
                { TopicType.TreasureHunters, Compatibility.Neutral },
                { TopicType.University, Compatibility.Excellent },
                { TopicType.Vampires, Compatibility.Excellent },
                { TopicType.Vikings, Compatibility.Terrible },
                { TopicType.Viruses, Compatibility.Terrible },
                { TopicType.War, Compatibility.Good },
                { TopicType.Werewolves, Compatibility.Neutral },
                { TopicType.WildWest, Compatibility.Neutral },
                { TopicType.Wizardry, Compatibility.Neutral },
                { TopicType.Zombies, Compatibility.Terrible }
            };

            // Add the pair to the Dictionary
            genreTopicCompatibilities.Add(GenreType.Romance, compatibleTopics);
        }

        /// <summary>
        /// Deploy all Science Fiction-Topic compatibilities
        /// </summary>
        private void DeployScienceFictionCompatibilities()
        {
            if (genreTopicCompatibilities == null) return;

            // Create a list to store the compatible topics
            Dictionary<TopicType, Compatibility> compatibleTopics = new()
            {
                { TopicType.Agents, Compatibility.Neutral },
                { TopicType.Airplanes, Compatibility.Poor },
                { TopicType.Aliens, Compatibility.Excellent },
                { TopicType.AncientCivilization, Compatibility.Terrible },
                { TopicType.Androids, Compatibility.Excellent },
                { TopicType.Angels, Compatibility.Terrible },
                { TopicType.Animals, Compatibility.Neutral },
                { TopicType.Apocalypse, Compatibility.Good },
                { TopicType.Archaeology, Compatibility.Poor },
                { TopicType.Archery, Compatibility.Terrible },
                { TopicType.Art, Compatibility.Neutral },
                { TopicType.Assassins, Compatibility.Neutral },
                { TopicType.Biology, Compatibility.Excellent },
                { TopicType.BountyHunters, Compatibility.Neutral },
                { TopicType.Cars, Compatibility.Neutral },
                { TopicType.Cards, Compatibility.Poor },
                { TopicType.Chemistry, Compatibility.Excellent },
                { TopicType.Chess, Compatibility.Poor },
                { TopicType.Cinema, Compatibility.Terrible },
                { TopicType.Circus, Compatibility.Terrible },
                { TopicType.Conspiracies, Compatibility.Neutral },
                { TopicType.Crime, Compatibility.Neutral },
                { TopicType.Curses, Compatibility.Terrible },
                { TopicType.Dancing, Compatibility.Terrible },
                { TopicType.Demons, Compatibility.Terrible },
                { TopicType.Detective, Compatibility.Good },
                { TopicType.Dinosaurs, Compatibility.Poor },
                { TopicType.Doctors, Compatibility.Neutral },
                { TopicType.Dogs, Compatibility.Terrible },
                { TopicType.Dolls, Compatibility.Terrible },
                { TopicType.Dragons, Compatibility.Terrible },
                { TopicType.Dreams, Compatibility.Excellent },
                { TopicType.Erotica, Compatibility.Neutral },
                { TopicType.Espionage, Compatibility.Neutral },
                { TopicType.Evolution, Compatibility.Excellent },
                { TopicType.Fey, Compatibility.Terrible },
                { TopicType.Fashion, Compatibility.Terrible },
                { TopicType.Food, Compatibility.Terrible },
                { TopicType.Gambling, Compatibility.Poor },
                { TopicType.Games, Compatibility.Excellent },
                { TopicType.Gangs, Compatibility.Terrible },
                { TopicType.Gladiators, Compatibility.Terrible },
                { TopicType.Gods, Compatibility.Terrible },
                { TopicType.Hacking, Compatibility.Excellent },
                { TopicType.Heaven, Compatibility.Terrible },
                { TopicType.Heist, Compatibility.Neutral },
                { TopicType.Hell, Compatibility.Terrible },
                { TopicType.Hitmen, Compatibility.Poor },
                { TopicType.Hunting, Compatibility.Terrible },
                { TopicType.Industrialization, Compatibility.Good },
                { TopicType.Insects, Compatibility.Terrible },
                { TopicType.Journalism, Compatibility.Neutral },
                { TopicType.Kaiju, Compatibility.Good },
                { TopicType.Language, Compatibility.Neutral },
                { TopicType.Mathematics, Compatibility.Good },
                { TopicType.Mecha, Compatibility.Excellent },
                { TopicType.Mermaids, Compatibility.Terrible },
                { TopicType.Military, Compatibility.Neutral },
                { TopicType.Mummies, Compatibility.Terrible },
                { TopicType.Music, Compatibility.Poor },
                { TopicType.Ninjas, Compatibility.Poor },
                { TopicType.ParallelWorld, Compatibility.Excellent },
                { TopicType.Pets, Compatibility.Terrible },
                { TopicType.Photography, Compatibility.Neutral },
                { TopicType.Physics, Compatibility.Excellent },
                { TopicType.Pirates, Compatibility.Terrible },
                { TopicType.Plants, Compatibility.Neutral },
                { TopicType.Police, Compatibility.Good },
                { TopicType.Politics, Compatibility.Good },
                { TopicType.Prison, Compatibility.Neutral },
                { TopicType.Religion, Compatibility.Poor },
                { TopicType.Revolution, Compatibility.Good },
                { TopicType.Samurai, Compatibility.Terrible },
                { TopicType.Sea, Compatibility.Neutral },
                { TopicType.SecretSociety, Compatibility.Neutral },
                { TopicType.Showbiz, Compatibility.Terrible },
                { TopicType.Singing, Compatibility.Terrible },
                { TopicType.Space, Compatibility.Excellent },
                { TopicType.Sports, Compatibility.Poor },
                { TopicType.StoneAge, Compatibility.Terrible },
                { TopicType.Superheroes, Compatibility.Good },
                { TopicType.Supervillains, Compatibility.Good },
                { TopicType.Survival, Compatibility.Terrible },
                { TopicType.TimeTravel, Compatibility.Excellent },
                { TopicType.TreasureHunters, Compatibility.Poor },
                { TopicType.University, Compatibility.Neutral },
                { TopicType.Vampires, Compatibility.Terrible },
                { TopicType.Vikings, Compatibility.Terrible },
                { TopicType.Viruses, Compatibility.Excellent },
                { TopicType.War, Compatibility.Neutral },
                { TopicType.Werewolves, Compatibility.Terrible },
                { TopicType.WildWest, Compatibility.Terrible },
                { TopicType.Wizardry, Compatibility.Terrible },
                { TopicType.Zombies, Compatibility.Good }
            };

            // Add the pair to the Dictionary
            genreTopicCompatibilities.Add(GenreType.ScienceFiction, compatibleTopics);
        }

        /// <summary>
        /// Deploy all Thriller-Topic compatibilities
        /// </summary>
        private void DeployThrillerCompatibilities()
        {
            if (genreTopicCompatibilities == null) return;

            // Create a list to store the compatible topics
            Dictionary<TopicType, Compatibility> compatibleTopics = new()
            {
                { TopicType.Agents, Compatibility.Good },
                { TopicType.Airplanes, Compatibility.Neutral },
                { TopicType.Aliens, Compatibility.Neutral },
                { TopicType.AncientCivilization, Compatibility.Terrible },
                { TopicType.Androids, Compatibility.Good },
                { TopicType.Angels, Compatibility.Poor },
                { TopicType.Animals, Compatibility.Terrible },
                { TopicType.Apocalypse, Compatibility.Neutral },
                { TopicType.Archaeology, Compatibility.Neutral },
                { TopicType.Archery, Compatibility.Terrible },
                { TopicType.Art, Compatibility.Neutral },
                { TopicType.Assassins, Compatibility.Excellent },
                { TopicType.Biology, Compatibility.Terrible },
                { TopicType.BountyHunters, Compatibility.Good },
                { TopicType.Cars, Compatibility.Terrible },
                { TopicType.Cards, Compatibility.Good },
                { TopicType.Chemistry, Compatibility.Terrible },
                { TopicType.Chess, Compatibility.Neutral },
                { TopicType.Cinema, Compatibility.Neutral },
                { TopicType.Circus, Compatibility.Neutral },
                { TopicType.Conspiracies, Compatibility.Good },
                { TopicType.Crime, Compatibility.Excellent },
                { TopicType.Curses, Compatibility.Good },
                { TopicType.Dancing, Compatibility.Terrible },
                { TopicType.Demons, Compatibility.Terrible },
                { TopicType.Detective, Compatibility.Excellent },
                { TopicType.Dinosaurs, Compatibility.Neutral },
                { TopicType.Doctors, Compatibility.Terrible },
                { TopicType.Dogs, Compatibility.Terrible },
                { TopicType.Dolls, Compatibility.Neutral },
                { TopicType.Dragons, Compatibility.Terrible },
                { TopicType.Dreams, Compatibility.Excellent },
                { TopicType.Erotica, Compatibility.Excellent },
                { TopicType.Espionage, Compatibility.Excellent },
                { TopicType.Evolution, Compatibility.Terrible },
                { TopicType.Fey, Compatibility.Good },
                { TopicType.Fashion, Compatibility.Terrible },
                { TopicType.Food, Compatibility.Terrible },
                { TopicType.Gambling, Compatibility.Good },
                { TopicType.Games, Compatibility.Neutral },
                { TopicType.Gangs, Compatibility.Good },
                { TopicType.Gladiators, Compatibility.Good },
                { TopicType.Gods, Compatibility.Poor },
                { TopicType.Hacking, Compatibility.Excellent },
                { TopicType.Heaven, Compatibility.Terrible },
                { TopicType.Heist, Compatibility.Excellent },
                { TopicType.Hell, Compatibility.Terrible },
                { TopicType.Hitmen, Compatibility.Excellent },
                { TopicType.Hunting, Compatibility.Neutral },
                { TopicType.Industrialization, Compatibility.Terrible },
                { TopicType.Insects, Compatibility.Poor },
                { TopicType.Journalism, Compatibility.Excellent },
                { TopicType.Kaiju, Compatibility.Terrible },
                { TopicType.Language, Compatibility.Terrible },
                { TopicType.Mathematics, Compatibility.Terrible },
                { TopicType.Mecha, Compatibility.Terrible },
                { TopicType.Mermaids, Compatibility.Neutral },
                { TopicType.Military, Compatibility.Neutral },
                { TopicType.Mummies, Compatibility.Neutral },
                { TopicType.Music, Compatibility.Neutral },
                { TopicType.Ninjas, Compatibility.Neutral },
                { TopicType.ParallelWorld, Compatibility.Good },
                { TopicType.Pets, Compatibility.Terrible },
                { TopicType.Photography, Compatibility.Good },
                { TopicType.Physics, Compatibility.Terrible },
                { TopicType.Pirates, Compatibility.Neutral },
                { TopicType.Plants, Compatibility.Neutral },
                { TopicType.Police, Compatibility.Excellent },
                { TopicType.Politics, Compatibility.Excellent },
                { TopicType.Prison, Compatibility.Good },
                { TopicType.Religion, Compatibility.Terrible },
                { TopicType.Revolution, Compatibility.Neutral },
                { TopicType.Samurai, Compatibility.Terrible },
                { TopicType.Sea, Compatibility.Good },
                { TopicType.SecretSociety, Compatibility.Excellent },
                { TopicType.Showbiz, Compatibility.Good },
                { TopicType.Singing, Compatibility.Terrible },
                { TopicType.Space, Compatibility.Excellent },
                { TopicType.Sports, Compatibility.Terrible },
                { TopicType.StoneAge, Compatibility.Terrible },
                { TopicType.Superheroes, Compatibility.Terrible },
                { TopicType.Supervillains, Compatibility.Excellent },
                { TopicType.Survival, Compatibility.Excellent },
                { TopicType.TimeTravel, Compatibility.Poor },
                { TopicType.TreasureHunters, Compatibility.Good },
                { TopicType.University, Compatibility.Neutral },
                { TopicType.Vampires, Compatibility.Good },
                { TopicType.Vikings, Compatibility.Terrible },
                { TopicType.Viruses, Compatibility.Neutral },
                { TopicType.War, Compatibility.Poor },
                { TopicType.Werewolves, Compatibility.Neutral },
                { TopicType.WildWest, Compatibility.Poor },
                { TopicType.Wizardry, Compatibility.Poor },
                { TopicType.Zombies, Compatibility.Good }
            };

            // Add the pair to the Dictionary
            genreTopicCompatibilities.Add(GenreType.Thriller, compatibleTopics);
        }
    }
}