using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace WriterTycoon.GameCreation.Topics
{
    [Serializable]
    public class Topic
    {
        public string Name { get; private set; }
        public bool IsUnlocked { get; private set; }
        public int MasteryLevel { get; private set; }

        public Topic(string name, bool unlocked)
        {
            Name = name;
            IsUnlocked = unlocked;
            MasteryLevel = 0;
        }

        /// <summary>
        /// Calculate the points generated by the Topic
        /// </summary>
        /// <param name="masteryLevel"></param>
        /// <returns></returns>
        public int CalculatePoints(int masteryLevel) => masteryLevel * 10;

        /// <summary>
        /// Unlock the Topic
        /// </summary>
        public void Unlock() => IsUnlocked = true;

        /// <summary>
        /// Increase the mastery of the Topic
        /// </summary>
        public void IncreaseMastery()
        {
            // Exit case - if the mastery level is already at 3
            if (MasteryLevel >= 3) return;

            // Increment the mastery level
            MasteryLevel++;
        }
    }
}